config/routes.rb
Rails.application.routes.draw do

  resources :opponents_wanted_posts do
    resource :user_opponents_post_relations, only: [:create, :destroy]
    collection do
      get 'search' # 検索条件入力ページ
      get 'result' # 検索結果表示ページ
    end
  end

  resources :friend_wanted_posts do
    collection do
      get 'search' # 検索条件入力ページ
      get 'result' # 検索結果表示ページ
    end
  end

  devise_for :users
  resources :users, only:[:show, :edit,:update]

  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root 'timelines#index', as: :authenticated_root
  end

  root 'welcome#index'

  
end

app/models/friend_wanted_post.rb
class FriendWantedPost < ApplicationRecord
  belongs_to :user
  serialize :target_game_ids, coder: YAML, type: Array

  validate :must_have_games

  private
  def must_have_games
    if target_game_ids.blank? || target_game_ids.reject(&:blank?).empty?
      errors.add(:base, "ゲームを少なくとも1つ選択してください")
    end
  end
end

app/controllers/friend_wanted_posts_controller.rb
class FriendWantedPostsController < ApplicationController
  before_action :set_friend_wanted_post, only: %i[ show edit update destroy ]

  # GET /friend_wanted_posts or /friend_wanted_posts.json
  def index
    @friend_wanted_posts = FriendWantedPost.all
  end

  # GET /friend_wanted_posts/1 or /friend_wanted_posts/1.json
  def show
  end

  # GET /friend_wanted_posts/new
  def new
    @friend_wanted_post = FriendWantedPost.new
  end

  # GET /friend_wanted_posts/1/edit
  def edit
  end

  # GET /friend_wanted_posts/search
  def search
  end

  # POST /friend_wanted_posts/search
  def result
    @friend_wanted_posts = FriendWantedPost.all

    #ゲームタイトルで絞る
    if params[:target_game_ids].present?
      @friend_wanted_posts = @friend_wanted_posts.where(target_game_ids: params[:target_game_ids])
    end
    
    #プレイスタイルで絞る
    if params[:play_style].present?
      @friend_wanted_posts = @friend_wanted_posts.where(play_style: params[:play_style])
    end

    render :result
  end

  # POST /friend_wanted_posts or /friend_wanted_posts.json
  def create
    @friend_wanted_post = FriendWantedPost.new(friend_wanted_post_params)

    @friend_wanted_post.user_id = current_user.id

    respond_to do |format|
      if @friend_wanted_post.save
        format.html { redirect_to @friend_wanted_post, notice: "Friend wanted post was successfully created." }
        format.json { render :show, status: :created, location: @friend_wanted_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend_wanted_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_wanted_posts/1 or /friend_wanted_posts/1.json
  def update
    respond_to do |format|
      if @friend_wanted_post.update(friend_wanted_post_params)
        format.html { redirect_to @friend_wanted_post, notice: "Friend wanted post was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @friend_wanted_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend_wanted_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_wanted_posts/1 or /friend_wanted_posts/1.json
  def destroy
    @friend_wanted_post.destroy!

    respond_to do |format|
      format.html { redirect_to friend_wanted_posts_path, notice: "Friend wanted post was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_wanted_post
      @friend_wanted_post = FriendWantedPost.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_wanted_post_params
      params.require(:friend_wanted_post).permit(:introduction, target_game_ids: [])
    end
end

app/helpers/friend_wanted_posts_helper.rb
module FriendWantedPostsHelper
end

app/views/friend_wanted_posts/_form.html.erb
<%= form_with(model: friend_wanted_post) do |form| %>
  <% if friend_wanted_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend_wanted_post.errors.count, "error") %> prohibited this friend_wanted_post from being saved:</h2>

      <ul>
        <% friend_wanted_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
  <label class="form-label fw-bold">募集するゲームを選択</label>
  <div class="d-flex flex-wrap gap-3">
    
    <% current_user.user_game_relations.includes(:game_title).each do |relation| %>
      <div class="form-check p-2 border rounded" style="background: #2b2b2b;">
        
        <%= form.check_box :target_game_ids, 
            { multiple: true, class: "form-check-input", include_hidden: false }, 
            relation.game_title_id, nil %>
            
        <label class="form-check-label text-white">
          <span class="fw-bold"><%= relation.game_title.name %></span><br>
          <span style="font-size: 0.8em; color: #5ce1e6;">
            <%= relation.play_style_name %>
          </span>
        </label>
      </div>
    <% end %>

  </div>
  </div>

  <div>
    <%= form.label :introduction, style: "display: block" %>
    <%= form.text_area :introduction %>
  </div>

  <div style="display: flex; justify-content: left; gap: 15px; margin-top: 20px;">
    <%= form.submit "保存する", 
        class: "btn submit",
        style: "background: #5ce1e6; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;" 
    %>

    <% back_path = @friend_wanted_post.new_record? ? root_path(tab: 'friend') : @friend_wanted_post %>

    <%= link_to "戻る", back_path, 
      class: "btn back",
      style: "background: #ccc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px; text-decoration: none; display: inline-flex; align-items: center; justify-content: center;"
    %>
  </div>
<% end %>

app/views/friend_wanted_posts/_friend_wanted_post.html.erb
<div id="<%= dom_id friend_wanted_post %>" class="gh-card">
  <div class="gh-card-header">
    <div class="gh-user-icon">
      <%= link_to user_path(friend_wanted_post.user) do %>
        <% if friend_wanted_post.user.photo.attached? %>
          <%= image_tag friend_wanted_post.user.photo, class: "user-img" %>
        <% else %>
          <div class="no-img"></div>
        <% end %>
      <% end %> 
    </div>
    <div class="gh-user-name">
      <%= friend_wanted_post.user.name%>
    </div>
  </div>

  <div class="gh-card-body">
    <div class="gh-info-list">

    <% 
       ids = friend_wanted_post.target_game_ids || []
       clean_ids = ids.map(&:to_i).reject { |id| id == 0 }
       target_relations = friend_wanted_post.user.user_game_relations.where(game_title_id: clean_ids) 
    %>
      <div class="gh-info-row">
        <span>性別🚺🚹：</span>
        <% case friend_wanted_post.user.gender%>
          <% when 1%>
            男性
          <% when 2%>
            女性
          <% when 3%>
            その他
          <% when 4%>
            非公開
          <% else %>
            未設定
          <% end %>
      </div>
      
      
      <span>よく遊ぶゲーム🎮</span>
      <div class="gh-info-row" style="margin-left: 20px;">  
        <div class="gh-tags-area">
          <% target_relations.each do |relation| %>
              <div class="border rounded px-3 py-2" style="background: #333; border-color: #5ce1e6 !important;">
                
                <span class="gh-tag-game" style="background-color: <%= game_color(relation.game_title.name) %>; color: <%= game_text_color(relation.game_title.name) %>;">
                  <%= relation.game_title.name %>
                </span>：

                <span class="gh-tag-game" style="background-color: #898989; color: #000000;">
                  <%= relation.play_style_name %>
                </span>
              </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>

  <div class="gh-created-at">
    <% if friend_wanted_post.created_at > 24.hours.ago %>
      <%= time_ago_in_words(friend_wanted_post.created_at) %> ago
    <% else %>
      <%= friend_wanted_post.created_at.strftime("%Y/%m/%d %H:%M") %>
    <% end %>
  </div>

  <div class="gh-description-area">
    <div class="gh-description-divider"></div>
    <p class="gh-description-text">
      <span class="gh-icon">💭</span>
      <%= friend_wanted_post.introduction %>
    </p>
  </div>

  <% unless action_name == "show" %>
    <%= link_to "詳細を見る", friend_wanted_post, class: "gh-card-footer-btn" %>
  <% end %>

</div>

app/views/friend_wanted_posts/edit.html.erb
<% content_for :title, "Editing friend wanted post" %>

<h1>Editing friend wanted post</h1>

<%= render "form", friend_wanted_post: @friend_wanted_post %>

<br>

app/views/friend_wanted_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Friend wanted posts" %>

<div id="friend_wanted_posts">
  <% @friend_wanted_posts.each do |friend_wanted_post| %>
    <%= render friend_wanted_post %>
  <% end %>
</div>

app/views/friend_wanted_posts/new.html.erb
<% content_for :title, "New friend wanted post" %>

<h1>New friend wanted post</h1>

<%= render "form", friend_wanted_post: @friend_wanted_post %>

<br>

app/views/friend_wanted_posts/result.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Friend wanted posts" %>
<div style="display: flex; justify-content: left; gap: 15px; margin-top: 20px;">
    <%= button_to "検索に戻る", search_friend_wanted_posts_path, 
        method: :get, 
        class: "btn back",
        style: "background: #7dd3fc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;"
    %>
</div>
<h1>検索結果</h1>

<div id="friend_wanted_posts">
  <% @friend_wanted_posts.each do |friend_wanted_post| %>
    <%= render friend_wanted_post %>
  <% end %>
</div>

app/views/friend_wanted_posts/search.html.erb
<div style="display: flex; justify-content: left; gap: 15px; margin-top: 20px;">
    <%= link_to "戻る", root_path(tab: 'friend'), 
        class: "btn back",
        style: "background: #7dd3fc; color: #000000; text-decoration: none; display: inline-block; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;"
    %>
</div>

<div class="gh-card">
    <div class="gh-card-header">
        <h1>募集を検索</h1>
    </div>

    <div class="gh-card-body">
    <%= form_with(url: result_friend_wanted_posts_path, method: :get, local: true) do |form| %>
      
        <div>
            <%= form.label :game_title_id, 'ゲームタイトル', class: "form-label fw-bold" %>
            <%= form.collection_select :game_title_id, GameTitle.all, :id, :name,{ include_blank: "指定なし" }, { class: "form-control" } %>
        </div>

        <div>
            <%= form.label :play_style, 'プレイスタイル', class: "form-label fw-bold" %>
            <%= form.select :play_style, 
                UserGameRelation::PLAY_STYLES.map { |s| [s[:name], s[:id]] }, 
                { include_blank: "指定なし" }, 
                { class: "form-control" }
            %>
        </div>

        
        <div class="text-center mt-4">
            <%= form.submit '検索する', class: "btn btn-primary" %>
        </div>
    <%end%>
    </div>
</div>

app/views/friend_wanted_posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div style="display: flex; justify-content: left; gap: 15px; margin-top: 20px;">
    <%= link_to "戻る", root_path(tab: 'friend', anchor: dom_id(@friend_wanted_post)), 
      class: "btn back",
      style: "background: #7dd3fc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px; text-decoration: none; display: inline-block;"
    %>
  </div>

<%= render @friend_wanted_post %>

<div class="gh-post-edit" style="display: flex; justify-content: center; gap: 15px; margin-top: 20px;">
    <% if current_user == @friend_wanted_post.user %>
      <%= button_to "編集", edit_friend_wanted_post_path(@friend_wanted_post), 
        method: :get, 
        class: "btn post-edit",
        style: "background-color: #7dd3fc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;" 
      %>
      <%= button_to "削除", @friend_wanted_post, 
        method: :delete, 
        class: "btn post-delete",
        style: "background: #ff6b6b; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;",
        form: { data: { turbo_confirm: "このポストを本当に削除してもよろしいですか？" } }
      %>
    <% end%>
  </div>