config/routes.rb
Rails.application.routes.draw do

  resources :opponents_wanted_posts do
    resource :user_opponents_post_relations, only: [:create, :destroy]
    collection do
      get 'search' # 検索条件入力ページ
      get 'result' # 検索結果表示ページ
    end
  end

  resources :friend_wanted_posts do
    collection do
      get 'search' # 検索条件入力ページ
      get 'result' # 検索結果表示ページ
    end
  end

  devise_for :users
  resources :users, only:[:show, :edit,:update]

  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root 'timelines#index', as: :authenticated_root
  end

  root 'welcome#index'

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_game_relations, dependent: :destroy
  has_many :user_titles, through: :user_game_relations
  has_many :opponents_wanted_post, dependent: :destroy
  has_many :user_opponents_post_relations, dependent: :destroy
  has_many :friend_wanted_posts

  accepts_nested_attributes_for :user_game_relations, allow_destroy:true #reject_if:all_blankですべて空欄の場合保存しないようにする
  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @user.user_game_relations.build if @user.user_game_relations.empty?
  end

  def update 
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice:"プロフィールを更新しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :photo, :gender, user_game_relations_attributes:[:id, :game_title_id, :play_style, :game_role_id, :game_role_2_id, :game_role_3_id, :game_mode_id, :game_mode_2_id, :_destroy])
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless @user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_game_relation_fields.html.erb
<div class="nested-form-wrapper game-input-group" 
     data-new-record="<%= f.object.new_record? %>"
     data-controller="game-dependency"
     data-game-dependency-modes-value='<%= GameMode.all.to_json %>'
     data-game-dependency-roles-value='<%= GameRole.all.to_json %>'>
  
  <div class="gh-game-edit-card">
    
    <div class="gh-game-edit-header">
      <%#ゲームタイトルの入力%>
      <%= f.label :game_title_id, "ゲームタイトル", class: "header-label" %>
      <%= f.collection_select :game_title_id, GameTitle.all, :id, :name, 
          { prompt: "選択してください" },
          { 
            class: "gh-select-title", 
            data: { target: "game-dependency.gameSelect", action: "change->game-dependency#updateOptions" } 
          } 
      %>
    </div>

    <div class="gh-game-edit-body">
      <%#プレイスタイルの入力%>
      <div class="gh-input-label">
        <span class="gh-icon-s">🔥</span> <label class="fw-bold">プレイスタイル</label>
      </div>
      <div class="mb-2">
        <%= f.select :play_style, 
            UserGameRelation::PLAY_STYLES.map { |s| [s[:name], s[:id]] }, 
            { include_blank: "選択してください" }, 
            { 
              class: "gh-select-item", 
              style: "width: 100%; box-sizing: border-box;" 
            } 
        %>
      </div>
      
      <div class="gh-input-section">
        <%#モードの入力%>
        <div class="gh-input-label">
          <span class="gh-icon-s">🎮</span> <label class="fw-bold">よく遊ぶモード (最大3つ)</label>
        </div>
        <% [:game_mode_id, :game_mode_2_id].each_with_index do |column, i| %>
          <div class="mb-2">
            <%= f.select column, [], { prompt: "#{i+1}. 先にゲームを選択" },
                { 
                  class: "gh-select-item",
                  data: { 
                    target: "game-dependency.modeSelect",
                    selected_value: f.object.public_send(column),
                    index: i + 1
                  }
                } 
            %>
          </div>
        <% end %>
      </div>

      <div class="gh-input-section">
        <%#ロール・キャラの入力%>
        <div class="gh-input-label">
           <span class="gh-icon-s">👤</span> <label class="fw-bold">よく使うキャラ (最大3つ)</label>
        </div>
        <% [:game_role_id, :game_role_2_id, :game_role_3_id].each_with_index do |column, i| %>
          <div class="mb-2">
            <%= f.select column, [], { prompt: "#{i+1}. 先にゲームを選択" },
                { 
                  class: "gh-select-item",
                  data: { 
                    target: "game-dependency.roleSelect", 
                    selected_value: f.object.public_send(column),
                    index: i + 1
                  }
                } 
            %>
          </div>
        <% end %>
      </div>

      <div class="gh-card-footer-action">
        <%= f.hidden_field :_destroy %>
        <%#よく遊ぶゲームの削除ボタン%>
        <button type="button" class="gh-delete-btn" data-action="click->nested-form#remove">
          削除
        </button>
      </div>

    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <%#名前の入力%>
  <div class="field">
    <%= f.label :name, "名前" %>
    <%= f.text_field :name %>
  </div>

  <%#アイコンのアップロード%>
  <div class="field">
  <%= f.label :photo, "アイコン" %>
  <%= f.file_field :photo %>
  </div>

  <%#自己紹介文の入力%>
  <div class="field">
    <%= f.label :introduction, "自己紹介" %>
    <%= f.text_area :introduction %>
  </div>

  <%#性別の入力%>
  <div class="field">
    <%= f.label :gender, "性別" %>
    <%= f.radio_button :gender, 1 %>
    <%= f.label :gender, "男性", value: 1 %>
    <%= f.radio_button :gender, 2 %>
    <%= f.label :gender, "女性", value: 2 %>
    <%= f.radio_button :gender, 3 %>
    <%= f.label :gender, "その他", value: 3 %>
    <%= f.radio_button :gender, 4 %>
    <%= f.label :gender, "非公開", value: 4 %>
  </div>

  <%#プレイするゲームの入力%>
  <h3>プレイするゲーム設定</h3>

  <div data-controller="nested-form">
    <%#user_game_relation_fields.html.erbを使用して入力%>
    <div data-nested-form-target="target">
      <%= f.fields_for :user_game_relations do |relation_form| %>
        <%= render partial: "user_game_relation_fields", locals:{ f: relation_form }%>
      <% end %>
    </div>

    <%#入力欄の追加%>
    <button type="button" class="btn btn-primary mt-3" data-action="click->nested-form#add" style="padding:6px 20px">
      + ゲームを追加する
    </button>

    <%#追加の際に作成する雛がた%>
    <template data-nested-form-target="template">
      <%= f.fields_for :user_game_relations, UserGameRelation.new, child_index: "NEW_RECORD" do |relation_form| %>
        <%= render partial: "user_game_relation_fields", locals:{f: relation_form }%>
      <% end %>
    </template>
    
  </div>

  <div class="actions mt-4" style="margin-top: 30px;">
    <%#変更を保存するボタン%>
    <%= f.submit "保存する", 
        class: "btn submit",
        style: "background: #5ce1e6; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;" 
    %> 
     <%#プロフィールページに戻るボタン%>
    <%= link_to "戻る", user_path, 
      class: "btn back",
      style: "background: #ccc; color: #000000; border: none; cursor: pointer; padding: 10px 30px; font-size: 1.1em; border-radius: 8px; text-decoration: none; display: inline-flex; align-items: center; justify-content: center;"
    %>
  </div>
<% end %>

<hr>

<div style="text-align: center;">
   <%#メールアドレスとパスワードの再設定ボタン%>
  <%= link_to "メールアドレス・パスワードの変更はこちら", edit_user_registration_path, 
      class: "btn",
      style: "background: #ccc; color: #333; text-decoration: none; padding: 8px 30px; font-size: 0.6em; border-radius: 8px; display: inline-block;" 
  %>
</div>

app/views/users/show.html.erb
<div class="gh-profile-name">
  <h1><%= @user.name %>のページ</h1>
</div>

<div class="gh-profile" style="display: flex;  gap: 15px; margin-top: 20px;"><%#横に並べる%>
  <%#アイコン画像の表示%>
  <div>
    <% if @user.photo.attached? %>
      <%= image_tag url_for(@user.photo), height: 150 %>
    <% else %>
      <%= image_tag "icon_temporary.png", height: 150 %>
    <% end %>
  </div>

  <div class="gh-profile-detail" style="display: block; gap 15x; margin-top: 0px"><%#縦に並べる%>
    <%#名前の表示%>
    <p>名前：<%= @user.name %></p>
    <%#性別の表示%>
    <p>性別：
      <% case @user.gender%>
      <% when 1%>
        男性
      <% when 2%>
        女性
      <% when 3%>
        その他
      <% when 4%>
        非公開
      <% else %>
        未設定
      <% end %>
    </p>
    <%#自己紹介文の表示%>
    <p>自己紹介：<%= @user.introduction %></p>
  </div>
</div>

<%#プレイするゲームの表示%>
<h2 class="mb-3 border-bottom pb-2">プレイするゲーム</h2>
<div class="game-card-grid">
  <% @user.user_game_relations.each do |relation| %>
    <%#選択したゲームの色の取得%>
    <% theme_color = game_color(relation.game_title.name) %>
    <% text_color  = game_text_color(relation.game_title.name) %>

    <div class="gh-game-edit-card compact" style="border-color: <%= theme_color %>;">
        <%#ゲームタイトルの表示%>
        <div class="gh-game-edit-header" style="background-color: <%= theme_color %>;">
          <div class="header-label" style="color: <%= text_color %>;">GAME TITLE</div>
          <div class="gh-select-title" style="cursor: default;">
            <%= relation.game_title.name %>
          </div>
        </div>

        <div class="gh-game-edit-body">
          
          <%#プレイスタイルの表示%>
          <div class="gh-input-section">
            <div class="gh-input-label">
              <span class="gh-icon-s">🔥</span> プレイスタイル
            </div>
            <div class="gh-select-item">
              <%= relation.play_style_name %>
            </div>
          </div>
          
          <%#モードの表示%>
          <div class="gh-input-section">
            <div class="gh-input-label">
              <span class="gh-icon-s">🎮</span> よく遊ぶモード
            </div>
            
            <div class="gh-select-item">
              <% modes = [relation.game_mode, relation.game_mode_2].compact %>
              <% if modes.present? %>
                <%= modes.map(&:name).join(' / ') %>
              <% else %>
                <span style="color: #888;">未設定</span>
              <% end %>
            </div>
          </div> 

          <%#キャラ・ロールの表示%>
          <div class="gh-input-section">
            <div class="gh-input-label">
              <span class="gh-icon-s">👤</span> よく使うキャラ・ロール
            </div>
            <div class="gh-select-item">
              <% roles = [relation.game_role, relation.game_role_2].compact %>
              <% if roles.present? %>
                <%= roles.map(&:name).join(' / ') %>
              <% else %>
                <span style="color: #888;">未設定</span>
              <% end %>
            </div>
          </div>

        </div>
      </div>
  <% end %>

  <%#よく遊ぶゲームが空だったら%>
  <% if @user.user_game_relations.empty? %>
    <div class="col-12">
      <p class="text-muted">まだゲームプロフィールが登録されていません。</p>
    </div>
  <% end %>
</div>

<div class="gh-profile-edit" style="display: flex; justify-content: center; gap: 15px; margin-top: 20px;">
  <%#自分のページなら%>
  <% if current_user == @user %>
    <%#編集ボタン%>
    <%= button_to "プロフィール編集", edit_user_path(@user), 
    method: :get, 
    class: "btn post-edit",
    style: "background-color: #7dd3fc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;" 
    %>  

    <%#パスワード変更ボタン%>
    <%= button_to "パスワード変更", edit_user_registration_path, 
    method: :get, 
    class: "btn post-edit",
    style: "background-color: #7dd3fc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;" 
    %>  

    <%#ログアウトボタン%>
    <%= button_to "ログアウト", destroy_user_session_path, 
      method: :delete, 
      class: "btn post-edit",
      style: "background-color: #7dd3fc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;" ,
      form: { data: { turbo_confirm: "ログアウトしてよろしいですか？" }, style: 'display:inline-block;'}
    %>  
  <% end %>
</div>