config/routes.rb
Rails.application.routes.draw do

  resources :opponents_wanted_posts do
    resource :user_opponents_post_relations, only: [:create, :destroy]
    collection do
      get 'search' # 検索条件入力ページ
      get 'result' # 検索結果表示ページ
    end
  end

  resources :friend_wanted_posts do
    collection do
      get 'search' # 検索条件入力ページ
      get 'result' # 検索結果表示ページ
    end
  end

  devise_for :users
  resources :users, only:[:show, :edit,:update]

  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root 'timelines#index', as: :authenticated_root
  end

  root 'welcome#index'

  
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    @active_tab = params[:tab] || 'opponent'

    if @active_tab == 'friend'
      #フレンド募集を取得
      @timeline_items = FriendWantedPost.order(created_at: :desc)
    else
      #相手募集を取得
      @timeline_items = OpponentsWantedPost.order(created_at: :desc)
  end
  end
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/timelines/index.html.erb
<%#ヘッダーのタブの表示%>
<% content_for :header do %>
  <header class="top-header">
    <%= link_to "相手募集", root_path(tab: 'opponent'), 
        class: "header-tab #{@active_tab == 'opponent' ? 'active' : ''}" %>

    <%= link_to "フレンド募集", root_path(tab: 'friend'), 
        class: "header-tab #{@active_tab == 'friend' ? 'active' : ''}" %>
  </header>
<% end %>

<%#検索ボタンの表示%>
<div style="display: flex; justify-content: left; gap: 15px; margin-top: 20px;">
  <% if @active_tab == 'friend' %>
    <%= button_to "🔍検索", search_friend_wanted_posts_path, 
        method: :get, 
        class: "btn back",
        style: "background: #7dd3fc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;"
    %>
  <% else %>
    <%= button_to "🔍検索", search_opponents_wanted_posts_path, 
        method: :get, 
        class: "btn back",
        style: "background: #7dd3fc; color: #000000; border: none; cursor: pointer; padding: 12px 30px; font-size: 1.1em; border-radius: 8px;"
    %>
  <% end %>
</div>

<%#投稿の表示%>
<div class="timelines">
  <%= render @timeline_items %>
</div>

<%#投稿作成ボタン%>
<% if @active_tab == 'friend' %>
  <%= link_to new_friend_wanted_post_path, class: "floating-btn" do %>
    <span style="font-size: 1.2em; margin-right: 5px;">＋</span> 募集する
  <% end %>
<% else %>
  <%= link_to new_opponents_wanted_post_path, class: "floating-btn" do %>
    <span style="font-size: 1.2em; margin-right: 5px;">＋</span> 募集する
  <% end %>
<% end %>